import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{execSync}from"node:child_process";import{computeUsageInvoiceAmountValue,hasRequiredScopesValue,isValidBillingPlanInputValue,shouldRevokeFamilyValue,shouldUseLiveProcessorValue}from"../lib/real-estate/enterprise/phase11-policy.js";
const source=path=>readFile(new URL(path,import.meta.url),"utf8");

test("OAuth refresh tokens are single-use; presenting a used or revoked one revokes the whole token family",async()=>{assert.equal(shouldRevokeFamilyValue(null,null),false);assert.equal(shouldRevokeFamilyValue("2026-01-01T00:00:00Z",null),true);assert.equal(shouldRevokeFamilyValue(null,"2026-01-01T00:00:00Z"),true);const text=await source("../lib/real-estate/enterprise/oauth.ts");assert.match(text,/if\(grant\.revokedAt\|\|grant\.usedAt\)/);assert.match(text,/eq\(realEstateOauthGrants\.familyId,grant\.familyId\)/);assert.match(text,/Refresh token reuse detected/)});

test("OAuth access tokens authenticate the public API alongside API keys, scope-checked the same way",async()=>{const text=await source("../lib/real-estate/enterprise/security.ts");assert.match(text,/raw\.startsWith\("slk_oauth_"\)/);assert.match(text,/authenticateOauthAccessToken/);assert.match(text,/grant\.scopes\.includes\(requiredScope\)/)});

test("consent is only honored when granted scopes are a strict superset of the requested scopes",()=>{assert.equal(hasRequiredScopesValue(["properties:read","leads:read"],["properties:read"]),true);assert.equal(hasRequiredScopesValue(["properties:read"],["properties:read","leads:read"]),false);assert.equal(hasRequiredScopesValue([],["properties:read"]),false)});

test("revoking a connected app revokes the consent record and every active grant for that client and member",async()=>{const text=await source("../lib/real-estate/enterprise/oauth.ts");const fn=text.slice(text.indexOf("export async function revokeConsent"));assert.match(fn,/realEstateOauthConsents\)\.set\(\{revokedAt:now\(\)/);assert.match(fn,/realEstateOauthGrants\)\.set\(\{revokedAt:now\(\)\}\)\.where\(and\(eq\(realEstateOauthGrants\.tenantId,scope\.tenantId\),eq\(realEstateOauthGrants\.clientId,clientId\),eq\(realEstateOauthGrants\.membershipId,membershipId\)/)});

test("marketplace billing has no hardcoded price, payment vendor, or Stripe onboarding wizard; defaults to a safe non-production preview processor",async()=>{const text=await source("../lib/real-estate/marketplace/billing.ts");assert.doesNotMatch(text,/stripe|paypal|braintree|adyen|square\.com/i);assert.match(text,/class PreviewPaymentProcessor/);assert.match(text,/process\.env\.NODE_ENV==="production"&&liveProcessor/);assert.equal(shouldUseLiveProcessorValue("development",true),false);assert.equal(shouldUseLiveProcessorValue("production",false),false);assert.equal(shouldUseLiveProcessorValue("production",true),true)});

test("billing plan creation requires an explicit non-negative integer amount and a known period; nothing is invented",async()=>{assert.equal(isValidBillingPlanInputValue("Pro","monthly",5000),true);assert.equal(isValidBillingPlanInputValue("","monthly",5000),false);assert.equal(isValidBillingPlanInputValue("Pro","weekly",5000),false);assert.equal(isValidBillingPlanInputValue("Pro","monthly",-1),false);assert.equal(isValidBillingPlanInputValue("Pro","monthly",49.99),false);const text=await source("../lib/real-estate/marketplace/billing.ts");assert.match(text,/amountCents:input\.amountCents/);assert.doesNotMatch(text,/amountCents:\s*[1-9]\d{2,}/)});

test("usage-based invoices sum metered usage against the plan's caller-defined per-unit price",()=>{assert.equal(computeUsageInvoiceAmountValue(10,500),5000);assert.equal(computeUsageInvoiceAmountValue(0,500),0);assert.equal(computeUsageInvoiceAmountValue(-5,500),0)});

test("no MLS/IDX vendor adapter, credentials, or contract terms were invented in Phase 11",async()=>{for(const file of["../lib/real-estate/enterprise/oauth.ts","../lib/real-estate/marketplace/billing.ts","../lib/real-estate/enterprise/security.ts"])assert.doesNotMatch(await source(file),/zillow|realtor\.com|mlsgrid|bridge interactive|spark api|\bRETS\b/i)});

test("Phase 11 migration is additive and complete",async()=>{const sql=await source("../drizzle/0010_phase11_oauth_billing.sql");for(const table of["real_estate_oauth_consents","real_estate_billing_plans","real_estate_billing_subscriptions","real_estate_billing_usage_records","real_estate_billing_invoices"])assert.match(sql,new RegExp(`CREATE TABLE "${table}"`));assert.doesNotMatch(sql,/DROP TABLE|TRUNCATE|DELETE FROM/)});

// app/api/contractor and app/contractor-admin are allowed to evolve over time by later,
// separate work (e.g. an additive professionType field) — what must hold permanently is
// that real-estate/OAuth/billing work never touches LFC payment code specifically.
test("contractor payment functionality and the Stripe onboarding wizard remain untouched by Phase 11",()=>{const diff=execSync("git diff --name-only 78357c9 -- lib/payments.ts",{encoding:"utf8"}).trim();assert.equal(diff,"","contractor payment files must not change in Phase 11")});

test("contractor, consumer, and portal modules remain outside Phase 11 real-estate additions",async()=>{for(const file of["../lib/real-estate/enterprise/oauth.ts","../lib/real-estate/marketplace/billing.ts"])assert.doesNotMatch(await source(file),/contractor|southline|\/homes|PIN authentication/i)});
