import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{detectSyncConflictValue,isValidDomainValue,isVersionCompatibleValue,legacyLicenseDefaultValue,rolloutBucketValue,rolloutDecisionValue}from"../lib/real-estate/marketplace/phase10-policy.js";
const source=path=>readFile(new URL(path,import.meta.url),"utf8");

test("provider catalog is versioned, capability-described, and vendor neutral",async()=>{const text=await source("../lib/real-estate/marketplace/types.ts");for(const category of["mls","idx","esignature","accounting","crm","marketing","analytics"])assert.match(text,new RegExp(`category:"${category}"`));assert.doesNotMatch(text,/zillow|realtor\.com|mlsgrid|bridge interactive|spark api|\bRETS\b|docusign|hubspot|salesforce/i);assert.match(text,/version:"1\.0\.0"/)});

test("provider version compatibility checks the major version only",()=>{assert.equal(isVersionCompatibleValue("1.0.0","1.4.2"),true);assert.equal(isVersionCompatibleValue("1.9.9","2.0.0"),false);assert.equal(isVersionCompatibleValue("0.0.0","1.0.0"),false)});

test("MLS/IDX sync is provider-neutral: no vendor adapter ships, unregistered providers no-op safely",async()=>{const text=await source("../lib/real-estate/marketplace/mls.ts");assert.doesNotMatch(text,/zillow|realtor\.com|mlsgrid|bridge interactive|spark api|\bRETS\b/i);assert.match(text,/NULL_ADAPTER/);assert.match(text,/registerMlsAdapter/);assert.match(text,/records:\[\],nextCursor:null/)});

test("MLS conflict detection compares incoming vs. stored external timestamps only after a prior sync",()=>{assert.equal(detectSyncConflictValue("2026-01-01T00:00:00Z","2026-02-01T00:00:00Z",true),true);assert.equal(detectSyncConflictValue("2026-03-01T00:00:00Z","2026-02-01T00:00:00Z",true),false);assert.equal(detectSyncConflictValue("2026-01-01T00:00:00Z","2026-02-01T00:00:00Z",false),false)});

test("marketplace installations encrypt credentials and never return them",async()=>{const text=await source("../lib/real-estate/marketplace/marketplace.ts");assert.match(text,/encryptSecret\(input\.apiKey,key\)/);const returns=[...text.matchAll(/credentialReference:undefined/g)];assert.ok(returns.length>=3,"install/configure/enable responses must all strip credentialReference")});

test("custom domain ownership is proven by an authoritative DNS TXT lookup, not the caller's claim",async()=>{const text=await source("../lib/real-estate/marketplace/branding.ts");assert.match(text,/resolveTxt\}from"node:dns\/promises"/);assert.match(text,/export async function verifyCustomDomain\(scope:\{tenantId:string;organizationId:string\},id:string\)/);assert.doesNotMatch(text,/verifyCustomDomain[^)]*observed/i)});

test("domain validation rejects malformed and reserved hosts",()=>{assert.equal(isValidDomainValue("offices.example.com"),true);assert.equal(isValidDomainValue("localhost"),false);assert.equal(isValidDomainValue("snaplink.com"),false);assert.equal(isValidDomainValue("not a domain"),false)});

test("tenant licensing keeps legacy surfaces on while gating new platform features off by default",()=>{assert.equal(legacyLicenseDefaultValue("crm"),true);assert.equal(legacyLicenseDefaultValue("transactions"),true);assert.equal(legacyLicenseDefaultValue("marketplace"),false);assert.equal(legacyLicenseDefaultValue("enterprise"),false)});

test("feature rollout strategies resolve deterministically per tenant",()=>{const bucketA=rolloutBucketValue("tenant-a","new_dashboard"),bucketAgain=rolloutBucketValue("tenant-a","new_dashboard");assert.equal(bucketA,bucketAgain);assert.equal(rolloutDecisionValue("all",0,[],bucketA,"tenant-a"),true);assert.equal(rolloutDecisionValue("off",0,[],bucketA,"tenant-a"),false);assert.equal(rolloutDecisionValue("allowlist",0,["tenant-a"],bucketA,"tenant-a"),true);assert.equal(rolloutDecisionValue("allowlist",0,["tenant-b"],bucketA,"tenant-a"),false);assert.equal(rolloutDecisionValue("percentage",100,[],bucketA,"tenant-a"),true);assert.equal(rolloutDecisionValue("percentage",0,[],bucketA,"tenant-a"),false)});

test("marketplace and enterprise-admin routes require durable membership authorization and tenant-scoped licensing",async()=>{const marketplace=await source("../app/api/real-estate/marketplace/route.ts"),admin=await source("../app/api/real-estate/enterprise-admin/[operation]/route.ts");assert.match(marketplace,/authorizeRealEstate\(req,"settings:manage"\)/);assert.match(marketplace,/hasFeature\(p\.tenantId,"marketplace"\)/);assert.match(admin,/authorizeRealEstate\(req,"settings:manage"\)/);assert.match(admin,/hasFeature\(p\.tenantId,"enterprise"\)/)});

test("Phase 10 migration is additive and complete",async()=>{const sql=await source("../drizzle/0009_phase10_marketplace_platform.sql");for(const table of["real_estate_mls_sync_cursors","real_estate_mls_entity_mappings","real_estate_tenant_branding","real_estate_custom_domains","real_estate_tenant_licenses","real_estate_tenant_lifecycle_events","real_estate_feature_rollouts","real_estate_platform_announcements"])assert.match(sql,new RegExp(`CREATE TABLE "${table}"`));assert.doesNotMatch(sql,/DROP TABLE|TRUNCATE|DELETE FROM/)});

test("contractor, consumer, portal, and existing enterprise modules remain outside Phase 10",async()=>{for(const file of["../lib/real-estate/marketplace/marketplace.ts","../lib/real-estate/marketplace/mls.ts","../lib/real-estate/marketplace/branding.ts","../lib/real-estate/marketplace/licensing.ts","../lib/real-estate/marketplace/admin.ts"])assert.doesNotMatch(await source(file),/contractor|southline|\/homes|PIN authentication/i)});
