import { createHash, randomUUID } from "node:crypto";
import { and, eq, isNull } from "drizzle-orm";
import { realEstateAppointments, realEstateCalendarConnections, realEstateCalendarEventLinks, realEstateOauthStates, realEstateOpenHouses, realEstateShowings } from "@/lib/db/schema";
import type { DataScope } from "../access";
import { isAgentScope } from "../access";
import { db } from "../repositories";
import { loadIntegrationConfig } from "./config";
import { decryptSecret, encryptSecret, safeHash, signOpaque, verifyOpaque } from "./crypto";
type Provider = "google" | "microsoft";
const now = () => new Date().toISOString(), id = (kind: string) => `re_${kind}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`;
const providerConfig = (provider: Provider, env = process.env) => {
  const config = loadIntegrationConfig(env), microsoftTenant = env.MICROSOFT_CALENDAR_TENANT || "common";
  if (provider === "google") return { configured: config.googleConfigured, clientId: env.GOOGLE_CALENDAR_CLIENT_ID, clientSecret: env.GOOGLE_CALENDAR_CLIENT_SECRET, redirectUri: env.GOOGLE_CALENDAR_REDIRECT_URI, authorize: "https://accounts.google.com/o/oauth2/v2/auth", token: "https://oauth2.googleapis.com/token", scope: "https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/calendar.calendarlist.readonly" };
  return { configured: config.microsoftConfigured, clientId: env.MICROSOFT_CALENDAR_CLIENT_ID, clientSecret: env.MICROSOFT_CALENDAR_CLIENT_SECRET, redirectUri: env.MICROSOFT_CALENDAR_REDIRECT_URI, authorize: `https://login.microsoftonline.com/${microsoftTenant}/oauth2/v2.0/authorize`, token: `https://login.microsoftonline.com/${microsoftTenant}/oauth2/v2.0/token`, scope: "offline_access Calendars.ReadWrite" };
};
export async function createOauthAuthorization(scope: DataScope, membershipId: string, provider: Provider) {
  const config = loadIntegrationConfig(), pc = providerConfig(provider); if (!pc.configured || !config.encryptionKey) throw new Error(`${provider} calendar is not configured`);
  const opaque = randomUUID(), expiresAt = new Date(Date.now() + 10 * 60_000).toISOString();
  await db().insert(realEstateOauthStates).values({ id: id("oauth"), tenantId: scope.tenantId, membershipId, provider, stateHash: safeHash(opaque), expiresAt });
  const state = signOpaque(opaque, config.encryptionKey), url = new URL(pc.authorize); url.searchParams.set("client_id", pc.clientId!); url.searchParams.set("redirect_uri", pc.redirectUri!); url.searchParams.set("response_type", "code"); url.searchParams.set("scope", pc.scope); url.searchParams.set("state", state); if (provider === "google") { url.searchParams.set("access_type", "offline"); url.searchParams.set("prompt", "consent"); }
  return url.toString();
}
export async function consumeOauthCallback(provider: Provider, signedState: string, code: string) {
  const config = loadIntegrationConfig(), pc = providerConfig(provider), opaque = config.encryptionKey ? verifyOpaque(signedState, config.encryptionKey) : null; if (!opaque) throw new Error("Invalid OAuth state");
  const state = (await db().select().from(realEstateOauthStates).where(and(eq(realEstateOauthStates.provider, provider), eq(realEstateOauthStates.stateHash, safeHash(opaque)), isNull(realEstateOauthStates.usedAt))).limit(1))[0];
  if (!state || new Date(state.expiresAt) < new Date()) throw new Error("OAuth state expired or already used");
  await db().update(realEstateOauthStates).set({ usedAt: now() }).where(and(eq(realEstateOauthStates.id, state.id), isNull(realEstateOauthStates.usedAt)));
  const response = await fetch(pc.token, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: pc.clientId!, client_secret: pc.clientSecret!, redirect_uri: pc.redirectUri!, grant_type: "authorization_code", code, scope: pc.scope }) });
  if (!response.ok) throw new Error("Calendar authorization exchange failed");
  const tokens = await response.json() as { access_token: string; refresh_token?: string; expires_in?: number };
  const existing = (await db().select().from(realEstateCalendarConnections).where(and(eq(realEstateCalendarConnections.tenantId, state.tenantId), eq(realEstateCalendarConnections.memberId, state.membershipId), eq(realEstateCalendarConnections.provider, provider), isNull(realEstateCalendarConnections.deletedAt))).limit(1))[0];
  const values = { status: "connected", syncEnabled: true, syncDirection: "outbound", attentionRequired: false, encryptionVersion: 1, accessTokenEncrypted: encryptSecret(tokens.access_token, config.encryptionKey!), refreshTokenEncrypted: tokens.refresh_token ? encryptSecret(tokens.refresh_token, config.encryptionKey!) : existing?.refreshTokenEncrypted || null, tokenExpiresAt: tokens.expires_in ? new Date(Date.now() + tokens.expires_in * 1000).toISOString() : null, lastErrorCode: null, lastErrorMessage: null, updatedAt: now() };
  if (existing) await db().update(realEstateCalendarConnections).set(values).where(and(eq(realEstateCalendarConnections.id, existing.id), eq(realEstateCalendarConnections.tenantId, state.tenantId)));
  else await db().insert(realEstateCalendarConnections).values({ id: id("calendar"), tenantId: state.tenantId, memberId: state.membershipId, provider, externalCalendarId: "primary", ...values });
  return { tenantId: state.tenantId, membershipId: state.membershipId };
}
export async function disconnectCalendar(scope: DataScope, membershipId: string, provider: Provider) {
  return (await db().update(realEstateCalendarConnections).set({ status: "disconnected", syncEnabled: false, accessTokenEncrypted: null, refreshTokenEncrypted: null, tokenExpiresAt: null, deletedAt: now(), updatedAt: now() }).where(and(eq(realEstateCalendarConnections.tenantId, scope.tenantId), eq(realEstateCalendarConnections.memberId, membershipId), eq(realEstateCalendarConnections.provider, provider), isNull(realEstateCalendarConnections.deletedAt))).returning({ id: realEstateCalendarConnections.id }))[0] ?? null;
}
export async function safeCalendarConnections(scope: DataScope, membershipId: string) {
  return db().select({ id: realEstateCalendarConnections.id, provider: realEstateCalendarConnections.provider, externalCalendarId: realEstateCalendarConnections.externalCalendarId, syncEnabled: realEstateCalendarConnections.syncEnabled, syncDirection: realEstateCalendarConnections.syncDirection, timezone: realEstateCalendarConnections.timezone, status: realEstateCalendarConnections.status, attentionRequired: realEstateCalendarConnections.attentionRequired, lastSyncedAt: realEstateCalendarConnections.lastSyncedAt, lastErrorCode: realEstateCalendarConnections.lastErrorCode, lastErrorMessage: realEstateCalendarConnections.lastErrorMessage }).from(realEstateCalendarConnections).where(and(eq(realEstateCalendarConnections.tenantId, scope.tenantId), eq(realEstateCalendarConnections.memberId, membershipId), isNull(realEstateCalendarConnections.deletedAt)));
}
export function decryptConnectionToken(encrypted: string, env = process.env) { const config = loadIntegrationConfig(env); if (!config.encryptionKey) throw new Error("Token encryption is unavailable"); return decryptSecret(encrypted, config.encryptionKey); }
export function calendarPayloadHash(payload: Record<string, unknown>) { return createHash("sha256").update(JSON.stringify(payload)).digest("hex"); }
async function internalEvent(scope:DataScope,type:string,eventId:string){
  if(type==="showing"){const x=(await db().select().from(realEstateShowings).where(and(eq(realEstateShowings.id,eventId),eq(realEstateShowings.tenantId,scope.tenantId),isNull(realEstateShowings.deletedAt),isAgentScope(scope)?eq(realEstateShowings.assignedAgentId,scope.agentId):undefined)).limit(1))[0];return x?{title:"Property showing",startsAt:x.requestedAt,endsAt:new Date(new Date(x.requestedAt).getTime()+3600000).toISOString()}:null}
  if(type==="open_house"){const x=(await db().select().from(realEstateOpenHouses).where(and(eq(realEstateOpenHouses.id,eventId),eq(realEstateOpenHouses.tenantId,scope.tenantId),isNull(realEstateOpenHouses.deletedAt),isAgentScope(scope)?eq(realEstateOpenHouses.assignedAgentId,scope.agentId):undefined)).limit(1))[0];return x?{title:"Open house",startsAt:x.startsAt,endsAt:x.endsAt}:null}
  if(type==="appointment"){const x=(await db().select().from(realEstateAppointments).where(and(eq(realEstateAppointments.id,eventId),eq(realEstateAppointments.tenantId,scope.tenantId),isNull(realEstateAppointments.deletedAt),isAgentScope(scope)?eq(realEstateAppointments.assignedAgentId,scope.agentId):undefined)).limit(1))[0];return x?{title:x.title,startsAt:x.startsAt,endsAt:x.endsAt||new Date(new Date(x.startsAt).getTime()+3600000).toISOString()}:null}return null;
}
async function calendarAccessToken(connection:typeof realEstateCalendarConnections.$inferSelect){
  const config=loadIntegrationConfig();if(!config.encryptionKey||!connection.accessTokenEncrypted)throw new Error("Calendar token unavailable");
  if(!connection.tokenExpiresAt||new Date(connection.tokenExpiresAt).getTime()>Date.now()+60000)return decryptSecret(connection.accessTokenEncrypted,config.encryptionKey);
  if(!connection.refreshTokenEncrypted)throw new Error("Calendar authorization revoked");
  const pc=providerConfig(connection.provider as Provider),refresh=decryptSecret(connection.refreshTokenEncrypted,config.encryptionKey),response=await fetch(pc.token,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:pc.clientId!,client_secret:pc.clientSecret!,grant_type:"refresh_token",refresh_token:refresh,scope:pc.scope})});if(!response.ok){await db().update(realEstateCalendarConnections).set({attentionRequired:true,status:"attention_required",lastErrorCode:"token_refresh_failed",updatedAt:now()}).where(and(eq(realEstateCalendarConnections.id,connection.id),eq(realEstateCalendarConnections.tenantId,connection.tenantId)));throw new Error("Calendar token refresh failed")}
  const tokens=await response.json()as{access_token:string;expires_in?:number;refresh_token?:string};await db().update(realEstateCalendarConnections).set({accessTokenEncrypted:encryptSecret(tokens.access_token,config.encryptionKey),refreshTokenEncrypted:tokens.refresh_token?encryptSecret(tokens.refresh_token,config.encryptionKey):connection.refreshTokenEncrypted,tokenExpiresAt:tokens.expires_in?new Date(Date.now()+tokens.expires_in*1000).toISOString():null,attentionRequired:false,status:"connected",updatedAt:now()}).where(and(eq(realEstateCalendarConnections.id,connection.id),eq(realEstateCalendarConnections.tenantId,connection.tenantId)));return tokens.access_token;
}
export async function synchronizeCalendarEvent(scope:DataScope,connectionId:string,eventType:string,eventId:string,operation:"upsert"|"delete"="upsert"){
  const connection=(await db().select().from(realEstateCalendarConnections).where(and(eq(realEstateCalendarConnections.id,connectionId),eq(realEstateCalendarConnections.tenantId,scope.tenantId),eq(realEstateCalendarConnections.syncEnabled,true),isNull(realEstateCalendarConnections.deletedAt))).limit(1))[0];if(!connection)throw new Error("Calendar connection unavailable");
  const calendarId=connection.externalCalendarId||"primary",link=(await db().select().from(realEstateCalendarEventLinks).where(and(eq(realEstateCalendarEventLinks.connectionId,connection.id),eq(realEstateCalendarEventLinks.tenantId,scope.tenantId),eq(realEstateCalendarEventLinks.internalEventType,eventType),eq(realEstateCalendarEventLinks.internalEventId,eventId),eq(realEstateCalendarEventLinks.externalCalendarId,calendarId))).limit(1))[0],token=await calendarAccessToken(connection);
  const base=connection.provider==="google"?`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`:`https://graph.microsoft.com/v1.0/me/calendars/${encodeURIComponent(calendarId)}/events`;
  if(operation==="delete"){if(!link?.externalEventId)return{status:"already_deleted"};const response=await fetch(`${base}/${encodeURIComponent(link.externalEventId)}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(!response.ok&&response.status!==404)throw new Error("Calendar delete failed");await db().update(realEstateCalendarEventLinks).set({status:"deleted",lastSyncedAt:now(),updatedAt:now()}).where(and(eq(realEstateCalendarEventLinks.id,link.id),eq(realEstateCalendarEventLinks.tenantId,scope.tenantId)));return{status:"deleted"}}
  const event=await internalEvent(scope,eventType,eventId);if(!event)throw new Error("Calendar event unavailable");const payload=connection.provider==="google"?{summary:event.title,start:{dateTime:event.startsAt,timeZone:connection.timezone},end:{dateTime:event.endsAt,timeZone:connection.timezone},extendedProperties:{private:{snaplinkEventId:eventId}}}:{subject:event.title,start:{dateTime:event.startsAt,timeZone:connection.timezone},end:{dateTime:event.endsAt,timeZone:connection.timezone},body:{contentType:"text",content:"Managed by SnapLink Real Estate."}},hash=calendarPayloadHash(payload);if(link?.synchronizedHash===hash)return{status:"unchanged",externalEventId:link.externalEventId};
  const response=await fetch(link?.externalEventId?`${base}/${encodeURIComponent(link.externalEventId)}`:base,{method:link?.externalEventId?"PATCH":"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("Calendar synchronization failed");const external=await response.json()as{id?:string;etag?:string;changeKey?:string};
  if(link)await db().update(realEstateCalendarEventLinks).set({externalEventId:external.id||link.externalEventId,providerEtag:external.etag||external.changeKey||null,synchronizedHash:hash,status:"synchronized",lastSyncedAt:now(),lastErrorCode:null,lastErrorMessage:null,updatedAt:now()}).where(and(eq(realEstateCalendarEventLinks.id,link.id),eq(realEstateCalendarEventLinks.tenantId,scope.tenantId)));else await db().insert(realEstateCalendarEventLinks).values({id:id("calendar_link"),tenantId:scope.tenantId,connectionId:connection.id,internalEventType:eventType,internalEventId:eventId,externalCalendarId:calendarId,externalEventId:external.id,providerEtag:external.etag||external.changeKey||null,synchronizedHash:hash,status:"synchronized",lastSyncedAt:now()}).onConflictDoNothing();
  await db().update(realEstateCalendarConnections).set({lastSyncedAt:now(),lastErrorCode:null,lastErrorMessage:null,updatedAt:now()}).where(and(eq(realEstateCalendarConnections.id,connection.id),eq(realEstateCalendarConnections.tenantId,scope.tenantId)));return{status:"synchronized",externalEventId:external.id};
}
export async function synchronizeCalendarConnection(scope:DataScope,connectionId:string){
  const [showings,houses,appointments]=await Promise.all([
    db().select({id:realEstateShowings.id}).from(realEstateShowings).where(and(eq(realEstateShowings.tenantId,scope.tenantId),isNull(realEstateShowings.deletedAt),isAgentScope(scope)?eq(realEstateShowings.assignedAgentId,scope.agentId):undefined)),
    db().select({id:realEstateOpenHouses.id}).from(realEstateOpenHouses).where(and(eq(realEstateOpenHouses.tenantId,scope.tenantId),isNull(realEstateOpenHouses.deletedAt),isAgentScope(scope)?eq(realEstateOpenHouses.assignedAgentId,scope.agentId):undefined)),
    db().select({id:realEstateAppointments.id}).from(realEstateAppointments).where(and(eq(realEstateAppointments.tenantId,scope.tenantId),isNull(realEstateAppointments.deletedAt),isAgentScope(scope)?eq(realEstateAppointments.assignedAgentId,scope.agentId):undefined)),
  ]);let synchronized=0;for(const[eventType,items]of[["showing",showings],["open_house",houses],["appointment",appointments]]as const)for(const item of items){await synchronizeCalendarEvent(scope,connectionId,eventType,item.id);synchronized++}return{synchronized};
}
