import { and, desc, eq, isNull, sql } from "drizzle-orm";
import { realEstateActivities, realEstateCommunicationEvents, realEstateCommunicationPreferences, realEstateCommunications, realEstateContactSuppressions, realEstateDeliverabilityDaily, realEstateJobs, realEstateProviderHealthChecks, realEstateWebhookEvents } from "@/lib/db/schema";
import { db } from "../repositories";
import type { DataScope } from "../access";
import { safeHash } from "./crypto";
const id = (kind: string) => `re_${kind}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`, now = () => new Date().toISOString();
const terminalRank: Record<string,number> = { queued:1, accepted:2, sent:3, deferred:3, delivered:6, opened:7, clicked:8, soft_bounce:5, hard_bounce:9, complaint:10, failed:9, sms_delivered:6, sms_failed:9, sms_undelivered:9, unsubscribed:10, sms_opt_out:10 };
export async function isSuppressed(tenantId: string, channel: string, recipient: string) { return Boolean((await db().select({ id: realEstateContactSuppressions.id }).from(realEstateContactSuppressions).where(and(eq(realEstateContactSuppressions.tenantId, tenantId), eq(realEstateContactSuppressions.channel, channel), eq(realEstateContactSuppressions.recipientHash, safeHash(recipient)), isNull(realEstateContactSuppressions.removedAt))).limit(1))[0]); }
export async function processWebhookEvent(webhookEventId: string) {
  const event = (await db().select().from(realEstateWebhookEvents).where(and(eq(realEstateWebhookEvents.id, webhookEventId), eq(realEstateWebhookEvents.signatureVerified, true))).limit(1))[0]; if (!event || event.status === "processed") return null;
  const providerMessageId = String(event.safeMetadata.providerMessageId || ""), communicationId = String(event.safeMetadata.communicationId || ""), occurredAt = String(event.safeMetadata.occurredAt || event.receivedAt);
  const communication = (await db().select().from(realEstateCommunications).where(communicationId ? eq(realEstateCommunications.id, communicationId) : and(eq(realEstateCommunications.provider, event.provider), eq(realEstateCommunications.providerMessageId, providerMessageId))).limit(1))[0];
  if (!communication) { await db().update(realEstateWebhookEvents).set({ status: "unmatched", processedAt: now(), updatedAt: now() }).where(eq(realEstateWebhookEvents.id, event.id)); return { matched: false }; }
  await db().transaction(async tx => {
    await tx.insert(realEstateCommunicationEvents).values({ id: id("delivery"), tenantId: communication.tenantId, communicationId: communication.id, provider: event.provider, eventType: event.eventType, providerEventId: event.providerEventId, occurredAt, safeMetadata: {} }).onConflictDoNothing();
    const currentRank = terminalRank[communication.status] || 0, nextRank = terminalRank[event.eventType] || 0;
    if (nextRank >= currentRank) { const status = ["delivered","sms_delivered"].includes(event.eventType) ? "delivered" : ["hard_bounce","complaint","failed","sms_failed","sms_undelivered"].includes(event.eventType) ? "failed" : ["sent","accepted","queued"].includes(event.eventType) ? "sent" : communication.status; await tx.update(realEstateCommunications).set({ status, deliveredAt: status === "delivered" ? occurredAt : communication.deliveredAt, error: status === "failed" ? event.eventType : communication.error, updatedAt: now() }).where(and(eq(realEstateCommunications.id, communication.id), eq(realEstateCommunications.tenantId, communication.tenantId))); }
    const suppressionType = event.eventType === "hard_bounce" ? "hard_bounce" : event.eventType === "complaint" ? "complaint" : event.eventType === "unsubscribed" ? "email_unsubscribe" : event.eventType === "sms_opt_out" ? "sms_stop" : null;
    if (suppressionType) { await tx.insert(realEstateContactSuppressions).values({ id: id("suppression"), tenantId: communication.tenantId, channel: communication.channel, recipientHash: safeHash(communication.recipient), suppressionType, source: event.provider }).onConflictDoNothing(); if (suppressionType === "email_unsubscribe") await tx.update(realEstateCommunicationPreferences).set({ emailOptIn: false, unsubscribedAt: occurredAt, updatedAt: now() }).where(and(eq(realEstateCommunicationPreferences.tenantId, communication.tenantId), eq(realEstateCommunicationPreferences.email, communication.recipient.toLowerCase()))); if (suppressionType === "sms_stop") { await tx.update(realEstateCommunicationPreferences).set({ smsOptIn: false, smsStoppedAt: occurredAt, updatedAt: now() }).where(and(eq(realEstateCommunicationPreferences.tenantId, communication.tenantId), eq(realEstateCommunicationPreferences.phone, communication.recipient))); const pending = await tx.update(realEstateCommunications).set({ status: "blocked", error: "Recipient opted out by SMS", updatedAt: now() }).where(and(eq(realEstateCommunications.tenantId, communication.tenantId), eq(realEstateCommunications.channel, "sms"), eq(realEstateCommunications.recipient, communication.recipient), sql`${realEstateCommunications.campaignId} is not null`, sql`${realEstateCommunications.status} in ('queued','scheduled')`)).returning({id:realEstateCommunications.id}); if(pending.length) await tx.update(realEstateJobs).set({status:"cancelled",cancelledAt:now(),updatedAt:now()}).where(and(eq(realEstateJobs.tenantId,communication.tenantId),eq(realEstateJobs.jobType,"communication.send"),sql`${realEstateJobs.payload}->>'communicationId' in (${sql.join(pending.map(x=>sql`${x.id}`),sql`,`)})`,sql`${realEstateJobs.status} in ('pending','available','scheduled','retry_wait')`)); await tx.insert(realEstateActivities).values({id:id("activity"),tenantId:communication.tenantId,entityType:"communication_preference",entityId:communication.id,action:"sms_opt_out",description:"SMS opt-out recorded",metadata:{source:event.provider}}); } }
    await tx.update(realEstateWebhookEvents).set({ status: "processed", processedAt: now(), updatedAt: now() }).where(eq(realEstateWebhookEvents.id, event.id));
  });
  return { matched: true, tenantId: communication.tenantId };
}
export async function deliverabilitySummary(scope: DataScope) {
  const [statuses, suppressions, daily, health] = await Promise.all([
    db().select({ key: realEstateCommunications.status, count: sql<number>`count(*)::int` }).from(realEstateCommunications).where(eq(realEstateCommunications.tenantId, scope.tenantId)).groupBy(realEstateCommunications.status),
    db().select({ count: sql<number>`count(*)::int` }).from(realEstateContactSuppressions).where(and(eq(realEstateContactSuppressions.tenantId, scope.tenantId), isNull(realEstateContactSuppressions.removedAt))),
    db().select().from(realEstateDeliverabilityDaily).where(eq(realEstateDeliverabilityDaily.tenantId, scope.tenantId)).orderBy(desc(realEstateDeliverabilityDaily.day)).limit(30),
    db().select().from(realEstateProviderHealthChecks).where(sql`${realEstateProviderHealthChecks.tenantId}=${scope.tenantId} or ${realEstateProviderHealthChecks.tenantId} is null`).orderBy(desc(realEstateProviderHealthChecks.checkedAt)).limit(20),
  ]); return { statuses, suppressionCount: suppressions[0]?.count || 0, daily, health };
}
