import type {
  Agent,
  Appointment,
  Brokerage,
  Property,
  RealEstateLead,
  RealEstateTenant,
  RealEstateUser,
} from "./types";

export const demoTenant: RealEstateTenant = {
  id: "re-demo-tenant",
  name: "Southline Realty Group",
  slug: "southline-realty",
  preferredLanguage: "en",
};

export const demoUser: RealEstateUser = {
  id: "re-demo-user",
  tenantId: demoTenant.id,
  name: "Elena Martinez",
  email: "elena@example.com",
  role: "broker_owner",
};

export const demoBrokerage: Brokerage = {
  id: "re-demo-brokerage",
  tenantId: demoTenant.id,
  name: demoTenant.name,
  description: "A relationship-led residential brokerage serving North Atlanta.",
  address: "125 Milton Avenue, Alpharetta, GA 30009",
  phone: "(770) 555-0100",
  website: "https://example.com",
  brokerName: "Elena Martinez",
  officeLocations: ["Alpharetta", "Atlanta"],
};

export const demoAgents: Agent[] = [
  {
    id: "re-agent-elena",
    tenantId: demoTenant.id,
    slug: "elena-martinez",
    name: "Elena Martinez",
    brokerageName: demoTenant.name,
    licenseNumber: "GA 412908",
    biography: "Thoughtful residential representation throughout North Atlanta.",
    languages: ["English", "Español"],
    serviceAreas: ["Alpharetta", "Milton", "Roswell"],
    specialties: ["Luxury residential", "Relocation", "New construction"],
    yearsExperience: 12,
    certifications: ["ABR", "SRS"],
    phone: "(678) 555-0142",
    email: "elena@example.com",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=85",
    published: true,
  },
];

export const demoProperties: Property[] = [
  {
    id: "re-property-hawthorne",
    tenantId: demoTenant.id,
    organizationId: "re-demo-organization",
    brokerageId: demoBrokerage.id,
    agentId: demoAgents[0].id,
    title: "Warm Modern Estate in Hawthorne Preserve",
    slug: "1428-hawthorne-ridge",
    status: "active",
    published: true,
    address: "1428 Hawthorne Ridge",
    country: "US",
    city: "Milton",
    state: "GA",
    postalCode: "30004",
    price: 1275000,
    bedrooms: 5,
    bathrooms: 4.5,
    squareFeet: 4280,
    lotSize: "1.02 acres",
    propertyType: "Single-family home",
    yearBuilt: 2019,
    mlsNumber: "GA-7482912",
    neighborhood: "Hawthorne Preserve",
    schoolDistrict: "Fulton County Schools",
    hoa: "$1,200 annually",
    taxes: "$9,840 annually",
    description: "A warm modern residence with refined natural materials and generous indoor-outdoor living.",
    shortDescription: "Warm modern living in Milton's Hawthorne Preserve.",
    features: ["Chef kitchen", "Main-level primary suite", "Home office", "Covered terrace"],
    amenities: ["Neighborhood trails", "Clubhouse", "Pool"],
    showingInstructions: "Appointment required.",
    openHouseDates: ["Saturday · 1–4 PM"],
    imageUrls: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=86"],
    viewCount: 1842,
    qrScanCount: 126,
    createdAt: "2026-07-01T12:00:00.000Z",
    updatedAt: "2026-07-28T12:00:00.000Z",
  },
  {
    id: "re-property-canton",
    tenantId: demoTenant.id,
    organizationId: "re-demo-organization",
    brokerageId: demoBrokerage.id,
    agentId: demoAgents[0].id,
    title: "Walkable Downtown Alpharetta Townhome",
    slug: "88-canton-street",
    status: "coming_soon",
    published: true,
    address: "88 Canton Street",
    country: "US",
    city: "Alpharetta",
    state: "GA",
    postalCode: "30009",
    price: 895000,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2640,
    lotSize: "0.18 acres",
    propertyType: "Townhome",
    yearBuilt: 2021,
    neighborhood: "Downtown Alpharetta",
    schoolDistrict: "Fulton County Schools",
    hoa: "$285 monthly",
    taxes: "$7,210 annually",
    description: "Walkable downtown living with tailored interiors and a private courtyard.",
    shortDescription: "Tailored townhome living in downtown Alpharetta.",
    features: ["Elevator", "Private courtyard", "Roof terrace"],
    amenities: ["Walkable dining", "Community green"],
    openHouseDates: [],
    imageUrls: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=86"],
    viewCount: 932,
    qrScanCount: 64,
    createdAt: "2026-07-10T12:00:00.000Z",
    updatedAt: "2026-07-29T12:00:00.000Z",
  },
  {
    id: "re-property-lake",
    tenantId: demoTenant.id,
    organizationId: "re-demo-organization",
    brokerageId: demoBrokerage.id,
    agentId: demoAgents[0].id,
    title: "Renovated Lakeside Home in Roswell",
    slug: "310-lake-summit-drive",
    status: "pending",
    published: true,
    address: "310 Lake Summit Drive",
    country: "US",
    city: "Roswell",
    state: "GA",
    postalCode: "30075",
    price: 745000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 3180,
    propertyType: "Single-family home",
    neighborhood: "Lake Summit",
    description: "A light-filled lakeside home with renovated interiors and a wooded setting.",
    shortDescription: "Renovated lakeside living in a quiet wooded setting.",
    features: ["Lake access", "Renovated kitchen", "Screened porch"],
    amenities: ["Community dock", "Pool"],
    openHouseDates: [],
    imageUrls: ["https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&q=86"],
    viewCount: 2215,
    qrScanCount: 188,
    createdAt: "2026-06-18T12:00:00.000Z",
    updatedAt: "2026-07-25T12:00:00.000Z",
  },
];

export const demoLeads: RealEstateLead[] = [
  { id: "re-lead-1", tenantId: demoTenant.id, assignedAgentId: demoAgents[0].id, type: "buyer", stage: "showing_scheduled", name: "Maya Thompson", email: "maya@example.com", phone: "(404) 555-0121", budget: "$850k–$1.1M", preferredCities: ["Milton", "Alpharetta"], timeline: "60–90 days", source: "Property QR", lastActivityAt: "2026-07-30T13:48:00.000Z" },
  { id: "re-lead-2", tenantId: demoTenant.id, type: "seller", stage: "seller_consultation", name: "Daniel Cho", email: "daniel@example.com", phone: "(678) 555-0164", preferredCities: ["Roswell"], timeline: "This fall", source: "Agent profile", lastActivityAt: "2026-07-30T13:12:00.000Z" },
  { id: "re-lead-3", tenantId: demoTenant.id, assignedAgentId: demoAgents[0].id, type: "buyer", stage: "qualified", name: "Sofia Ramirez", email: "sofia@example.com", phone: "(770) 555-0199", budget: "$600k–$750k", preferredCities: ["Johns Creek"], timeline: "3–6 months", source: "Open house", lastActivityAt: "2026-07-30T11:30:00.000Z" },
];

export const demoAppointments: Appointment[] = [
  { id: "re-appt-1", tenantId: demoTenant.id, agentId: demoAgents[0].id, propertyId: demoProperties[0].id, leadId: demoLeads[0].id, type: "property_showing", startsAt: "2026-07-30T18:30:00.000Z", status: "confirmed" },
  { id: "re-appt-2", tenantId: demoTenant.id, agentId: demoAgents[0].id, leadId: demoLeads[1].id, type: "seller_consultation", startsAt: "2026-07-30T21:00:00.000Z", status: "confirmed" },
];

export function formatPropertyPrice(price: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(price);
}
