import{NextRequest,NextResponse}from"next/server";import{authorizeRealEstate}from"@/lib/real-estate/auth";import{hasFeature}from"@/lib/real-estate/marketplace/licensing";import{activeAnnouncements,listFeatureRollouts,listIncidents,publishAnnouncement,recordTenantLifecycleEvent,resolveIncident,setFeatureRollout,tenantLifecycleHistory}from"@/lib/real-estate/marketplace/admin";
export async function GET(req:NextRequest,ctx:{params:Promise<{operation:string}>}){const{operation}=await ctx.params,p=await authorizeRealEstate(req,"settings:manage");if(!p)return NextResponse.json({error:"Enterprise administration permission required"},{status:403});if(!await hasFeature(p.tenantId,"enterprise"))return NextResponse.json({error:"Enterprise administration is not licensed for this tenant"},{status:403});if(operation==="incidents")return NextResponse.json({incidents:await listIncidents(p.tenantId)});if(operation==="rollouts")return NextResponse.json({rollouts:await listFeatureRollouts()});if(operation==="announcements")return NextResponse.json({announcements:await activeAnnouncements(p.tenantId)});if(operation==="lifecycle")return NextResponse.json({events:await tenantLifecycleHistory(p.tenantId)});return NextResponse.json({error:"Operation not found"},{status:404})}
export async function POST(req:NextRequest,ctx:{params:Promise<{operation:string}>}){const{operation}=await ctx.params,p=await authorizeRealEstate(req,"settings:manage");if(!p)return NextResponse.json({error:"Enterprise administration permission required"},{status:403});if(!await hasFeature(p.tenantId,"enterprise"))return NextResponse.json({error:"Enterprise administration is not licensed for this tenant"},{status:403});const body=await req.json();try{
  if(operation==="lifecycle")return NextResponse.json({event:await recordTenantLifecycleEvent(p.tenantId,body.eventType,p.userEmail,body.reason)},{status:201});
  if(operation==="incidents")return NextResponse.json({incident:await resolveIncident(String(body.incidentId||""))});
  if(operation==="rollouts")return NextResponse.json({rollout:await setFeatureRollout(p.membershipId,body)},{status:201});
  if(operation==="announcements")return NextResponse.json({announcement:await publishAnnouncement(p.membershipId,body)},{status:201});
  return NextResponse.json({error:"Operation not found"},{status:404});
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Invalid request"},{status:400})}}
