import"server-only";import{randomBytes,timingSafeEqual,createHash,createHmac}from"node:crypto";import{and,eq,isNull,or,sql}from"drizzle-orm";import{realEstateApiKeys,realEstateAuditEvents,realEstateOauthClients,realEstateOauthGrants}from"@/lib/db/schema";import{db}from"../repositories";import type{NextRequest}from"next/server";import type{ApiPrincipal}from"./types";
const uid=(k:string)=>`re_${k}_${crypto.randomUUID()}`,now=()=>new Date().toISOString(),hash=(v:string)=>createHash("sha256").update(v).digest("hex"),month=()=>now().slice(0,7);
export function opaqueId(prefix:string){return`${prefix}_${randomBytes(12).toString("base64url")}`}
export function encodeCursor(value:{createdAt:string;id:string}){const data=Buffer.from(JSON.stringify(value)).toString("base64url"),key=process.env.REAL_ESTATE_API_CURSOR_SECRET||process.env.REAL_ESTATE_JOB_PROCESSOR_SECRET||"development-only";return`${data}.${createHmac("sha256",key).update(data).digest("base64url")}`}
export function decodeCursor(cursor:string|null){if(!cursor)return null;try{const[data,sig]=cursor.split("."),expected=encodeCursor(JSON.parse(Buffer.from(data,"base64url").toString())).split(".")[1];if(!sig||sig.length!==expected.length||!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const value=JSON.parse(Buffer.from(data,"base64url").toString());return typeof value.id==="string"&&typeof value.createdAt==="string"?value:null}catch{return null}}
export async function createApiKey(scope:{tenantId:string;organizationId:string},membershipId:string,input:{name:string;scopes:string[];ipAllowlist?:string[];requestsPerMinute?:number;monthlyQuota?:number;expiresAt?:string}){const secret=`slk_live_${randomBytes(32).toString("base64url")}`,prefix=secret.slice(0,18),record=(await db().insert(realEstateApiKeys).values({id:uid("apikey"),tenantId:scope.tenantId,organizationId:scope.organizationId,externalId:opaqueId("key"),name:input.name.trim().slice(0,120),keyPrefix:prefix,secretHash:hash(secret),scopes:input.scopes,ipAllowlist:input.ipAllowlist||[],requestsPerMinute:Math.min(1000,Math.max(1,input.requestsPerMinute||60)),monthlyQuota:Math.min(10_000_000,Math.max(1,input.monthlyQuota||10000)),expiresAt:input.expiresAt,createdByMembershipId:membershipId}).returning())[0];await db().insert(realEstateAuditEvents).values({id:uid("audit"),tenantId:scope.tenantId,organizationId:scope.organizationId,actorType:"membership",actorMembershipId:membershipId,action:"api_key_created",resourceType:"api_key",resourceId:record.id,safeMetadata:{externalId:record.externalId,scopes:record.scopes}});return{record:{...record,secretHash:undefined},secret}}
const rate=new Map<string,{count:number;reset:number}>();
export async function authenticateApi(req:NextRequest,requiredScope:string):Promise<ApiPrincipal|null>{const raw=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||req.headers.get("x-api-key");if(!raw||!raw.startsWith("slk_"))return null;if(raw.startsWith("slk_oauth_"))return authenticateOauthAccessToken(raw,requiredScope);const prefix=raw.slice(0,18),row=(await db().select().from(realEstateApiKeys).where(and(eq(realEstateApiKeys.keyPrefix,prefix),isNull(realEstateApiKeys.revokedAt),or(isNull(realEstateApiKeys.expiresAt),sql`${realEstateApiKeys.expiresAt}>now()`))).limit(1))[0];if(!row||hash(raw)!==row.secretHash||!row.scopes.includes(requiredScope))return null;const ip=(req.headers.get("x-forwarded-for")||"").split(",")[0].trim();if(row.ipAllowlist.length&&!row.ipAllowlist.includes(ip))return null;const current=rate.get(row.id),time=Date.now();if(!current||current.reset<=time)rate.set(row.id,{count:1,reset:time+60000});else if(++current.count>row.requestsPerMinute)throw Object.assign(new Error("Rate limit exceeded"),{status:429,code:"rate_limit_exceeded"});const usedMonth=row.usageMonth===month()?row.usageCount:0;if(usedMonth>=row.monthlyQuota)throw Object.assign(new Error("Monthly quota exceeded"),{status:429,code:"quota_exceeded"});await db().update(realEstateApiKeys).set({usageMonth:month(),usageCount:usedMonth+1,lastUsedAt:now(),updatedAt:now()}).where(and(eq(realEstateApiKeys.id,row.id),eq(realEstateApiKeys.tenantId,row.tenantId)));return{tenantId:row.tenantId,organizationId:row.organizationId,apiKeyId:row.id,scopes:row.scopes}}
// Phase 11: OAuth access tokens (issued by enterprise/oauth.ts) authenticate the same public API
// surface as API keys. A fixed conservative per-minute cap applies since OAuth clients, unlike API
// keys, have no per-client requestsPerMinute column.
async function authenticateOauthAccessToken(raw:string,requiredScope:string):Promise<ApiPrincipal|null>{const grant=(await db().select().from(realEstateOauthGrants).where(and(eq(realEstateOauthGrants.tokenHash,hash(raw)),eq(realEstateOauthGrants.grantType,"access_token"),isNull(realEstateOauthGrants.revokedAt),sql`${realEstateOauthGrants.expiresAt}>now()`)).limit(1))[0];if(!grant||!grant.scopes.includes(requiredScope))return null;const client=(await db().select().from(realEstateOauthClients).where(and(eq(realEstateOauthClients.clientId,grant.clientId),isNull(realEstateOauthClients.revokedAt))).limit(1))[0];if(!client)return null;const current=rate.get(grant.id),time=Date.now();if(!current||current.reset<=time)rate.set(grant.id,{count:1,reset:time+60000});else if(++current.count>300)throw Object.assign(new Error("Rate limit exceeded"),{status:429,code:"rate_limit_exceeded"});return{tenantId:grant.tenantId,organizationId:client.organizationId,oauthGrantId:grant.id,scopes:grant.scopes}}
export function apiError(status:number,code:string,message:string,requestId:string){return{errors:[{status:String(status),code,title:message}],meta:{requestId,apiVersion:"2026-07-01"}}}
