import "server-only";import type{RealEstateAiConfig,RealEstateAiProviderType}from"./types";
const bool=(v:string|undefined,f=false)=>v===undefined?f:v==="true",bounded=(v:string|undefined,f:number,min:number,max:number)=>{const n=Number(v??f);if(!Number.isInteger(n)||n<min||n>max)throw new Error("Invalid bounded AI configuration");return n};
const MODELS={openai:["gpt-4.1-mini","gpt-4.1","text-embedding-3-small"],anthropic:["claude-sonnet-4-20250514","claude-3-5-haiku-latest"],mock:["mock-safe-v1"],disabled:["disabled"]}as const;
export function loadAiConfig(env:NodeJS.ProcessEnv=process.env):RealEstateAiConfig{
 const testMode=env.NODE_ENV==="test"||bool(env.REAL_ESTATE_AI_TEST_MODE),requested=(env.REAL_ESTATE_AI_PROVIDER||((env.NODE_ENV==="production")?"disabled":"mock"))as RealEstateAiProviderType,provider=testMode?"mock":requested;if(!Object.keys(MODELS).includes(provider))throw new Error("Unsupported AI provider");
 const enabled=testMode||bool(env.REAL_ESTATE_AI_ENABLED,false),defaults=provider==="openai"?MODELS.openai:provider==="anthropic"?MODELS.anthropic:MODELS[provider],defaultModel=env.REAL_ESTATE_AI_DEFAULT_MODEL||defaults[0],fastModel=env.REAL_ESTATE_AI_FAST_MODEL||defaultModel,structuredModel=env.REAL_ESTATE_AI_STRUCTURED_MODEL||defaultModel,embeddingModel=env.REAL_ESTATE_AI_EMBEDDING_MODEL||(provider==="openai"?"text-embedding-3-small":defaultModel),allowedModels=new Set<string>(defaults);
 for(const model of[defaultModel,fastModel,structuredModel,embeddingModel])if(!allowedModels.has(model))throw new Error("AI model is not allowlisted");
 const credential=provider==="openai"?env.OPENAI_API_KEY:provider==="anthropic"?env.ANTHROPIC_API_KEY:undefined;if(enabled&&env.NODE_ENV==="production"&&["openai","anthropic"].includes(provider)&&!credential)throw new Error("AI provider credential is not configured");
 return{enabled,provider,defaultModel,fastModel,structuredModel,embeddingModel,allowedModels,maxInputTokens:bounded(env.REAL_ESTATE_AI_MAX_INPUT_TOKENS,12000,256,100000),maxOutputTokens:bounded(env.REAL_ESTATE_AI_MAX_OUTPUT_TOKENS,1800,64,16000),monthlyTenantLimit:bounded(env.REAL_ESTATE_AI_MONTHLY_TENANT_LIMIT,500,1,1000000),dailyUserLimit:bounded(env.REAL_ESTATE_AI_DAILY_USER_LIMIT,25,1,10000),redactionEnabled:bool(env.REAL_ESTATE_AI_REDACTION_ENABLED,true),logContent:false,testMode,timeoutMs:bounded(env.REAL_ESTATE_AI_TIMEOUT_MS,30000,1000,120000),maxConcurrent:bounded(env.REAL_ESTATE_AI_MAX_CONCURRENT,3,1,25),credential};
}
