import"server-only";import{and,eq,isNull,lt}from"drizzle-orm";import{realEstateAiHealthChecks,realEstateAiRequests,realEstateAiResults,realEstateAuditEvents,realEstateLeadScores,realEstateLeads,realEstateProperties}from"@/lib/db/schema";import{db}from"../repositories";import type{DataScope}from"../access";import{isAgentScope}from"../access";import{loadAiConfig}from"./config";import{checkFairHousing}from"./guardrails";import{aiOrganization,getAiSettings}from"./repositories";import{gradeForScore}from"./schemas";
const uid=(k:string)=>`re_${k}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,10)}`,now=()=>new Date().toISOString();
export async function applyAiResult(scope:DataScope,membershipId:string,resultId:string,input:{fullDescription?:string;shortDescription?:string}){
 const row=(await db().select({request:realEstateAiRequests,result:realEstateAiResults}).from(realEstateAiResults).innerJoin(realEstateAiRequests,eq(realEstateAiResults.requestId,realEstateAiRequests.id)).where(and(eq(realEstateAiResults.id,resultId),eq(realEstateAiRequests.tenantId,scope.tenantId),isNull(realEstateAiResults.deletedAt),isNull(realEstateAiRequests.deletedAt))).limit(1))[0];if(!row||!row.result.approvedAt||row.result.rejectedAt||row.result.staleAt||row.result.appliedAt)throw new Error("Approved current AI result required");
 if(row.request.feature!=="property_description"||row.request.sourceType!=="property")throw new Error("This AI result cannot be applied through this action");const property=(await db().select().from(realEstateProperties).where(and(eq(realEstateProperties.id,row.request.sourceId),eq(realEstateProperties.tenantId,scope.tenantId),isNull(realEstateProperties.deletedAt),isAgentScope(scope)?eq(realEstateProperties.listingAgentId,scope.agentId):undefined)).limit(1))[0];if(!property)throw new Error("Source record unavailable");
 const full=(input.fullDescription||String(row.result.structuredPayload.fullDescription||"")).trim(),short=(input.shortDescription||String(row.result.structuredPayload.shortDescription||"")).trim();if(!full||!short)throw new Error("Description fields are required");const guard=checkFairHousing(`${full}\n${short}`);if(!guard.safe)throw new Error(guard.explanation);
 const stamp=now();await db().transaction(async tx=>{await tx.update(realEstateProperties).set({description:full,shortDescription:short,updatedAt:stamp}).where(and(eq(realEstateProperties.id,property.id),eq(realEstateProperties.tenantId,scope.tenantId)));await tx.update(realEstateAiResults).set({appliedAt:stamp,updatedAt:stamp}).where(eq(realEstateAiResults.id,resultId));await tx.insert(realEstateAuditEvents).values({id:uid("audit"),tenantId:scope.tenantId,organizationId:row.request.organizationId,actorType:"membership",actorMembershipId:membershipId,action:"ai_output_applied",resourceType:"property",resourceId:property.id,safeMetadata:{resultId,fields:["description","shortDescription"],published:false}})});return{applied:true,published:false};
}
export async function overrideLeadScore(scope:DataScope,membershipId:string,leadId:string,input:{score:number;reason:string}){if(!Number.isInteger(input.score)||input.score<0||input.score>100||!input.reason?.trim())throw new Error("Score from 0 to 100 and audit reason are required");const lead=(await db().select().from(realEstateLeads).where(and(eq(realEstateLeads.id,leadId),eq(realEstateLeads.tenantId,scope.tenantId),isNull(realEstateLeads.deletedAt),isAgentScope(scope)?eq(realEstateLeads.assignedAgentId,scope.agentId):undefined)).limit(1))[0],organizationId=await aiOrganization(scope);if(!lead||!organizationId)throw new Error("Lead unavailable");const record=(await db().insert(realEstateLeadScores).values({id:uid("leadscore"),tenantId:scope.tenantId,organizationId,leadId,score:input.score,grade:gradeForScore(input.score),confidence:100,factors:[{key:"manual_override",label:"Human review",impact:"neutral",explanation:"An authorized professional manually set this advisory score."}],missingSignals:[],sourceHash:`manual:${lead.updatedAt}`,isManualOverride:true,overrideReason:input.reason.trim().slice(0,500),overriddenByMembershipId:membershipId}).returning())[0];await db().insert(realEstateAuditEvents).values({id:uid("audit"),tenantId:scope.tenantId,organizationId,actorType:"membership",actorMembershipId:membershipId,action:"lead_score_manually_overridden",resourceType:"lead",resourceId:leadId,safeMetadata:{score:input.score,reason:input.reason.trim().slice(0,500)}});return record}
export async function recordAiHealth(){const config=loadAiConfig(),status=!config.enabled?"disabled":(["openai","anthropic"].includes(config.provider)&&!config.credential)?"unconfigured":"healthy",stamp=now();return(await db().insert(realEstateAiHealthChecks).values({id:uid("aihealth"),provider:config.provider,model:config.defaultModel,status,checkedAt:stamp,...(status==="healthy"?{lastSuccessAt:stamp}:{})}).returning())[0]}
export async function runAiRetention(scope:DataScope){const config=loadAiConfig(),settings=await getAiSettings(scope,config);if(!settings)return{cleaned:0};const cutoff=new Date(Date.now()-settings.retentionDays*86400000).toISOString(),rejected=await db().update(realEstateAiResults).set({renderedText:"",structuredPayload:{retained:false,reason:"tenant_retention_policy"},updatedAt:now(),deletedAt:now()}).where(and(eq(realEstateAiResults.tenantId,scope.tenantId),lt(realEstateAiResults.rejectedAt,cutoff),isNull(realEstateAiResults.deletedAt))).returning({id:realEstateAiResults.id});await db().update(realEstateAiRequests).set({providerRequestId:null,updatedAt:now()}).where(and(eq(realEstateAiRequests.tenantId,scope.tenantId),lt(realEstateAiRequests.completedAt,cutoff)));return{cleaned:rejected.length}}
