import { and, eq, isNull } from "drizzle-orm";
import { realEstateAuditEvents, realEstateEscrowEvents, realEstateEscrowRecords, realEstateInspections, realEstateInspectionItems, realEstateReminders, realEstateRepairRequests, realEstateRepairUpdates, realEstateTransactionMilestones, realEstateTransactionParticipants } from "@/lib/db/schema";
import { db } from "../repositories"; import type { DataScope } from "../access"; import { findTransaction } from "./repository"; import { enqueueCalendarJobs, enqueueJob } from "../jobs";
const uid=(kind:string)=>`re_${kind}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,10)}`,now=()=>new Date().toISOString();
const inspectionStatuses=["not_scheduled","scheduled","completed","report_received","repairs_requested","repairs_in_progress","repairs_completed","follow_up_required","closed"];
const escrowStatuses=["not_required","pending","due","deposited","verified","held","released","returned","forfeited","disputed"];
async function audit(scope:DataScope,membershipId:string,organizationId:string,transactionId:string,type:string,id:string,action:string){await db().insert(realEstateAuditEvents).values({id:uid("audit"),tenantId:scope.tenantId,organizationId,actorType:"membership",actorMembershipId:membershipId,action,resourceType:type,resourceId:id,transactionId})}
export async function saveInspection(scope:DataScope,membershipId:string,transactionId:string,input:Record<string,unknown>){
 const transaction=await findTransaction(scope,transactionId);if(!transaction)throw new Error("Transaction unavailable");const status=String(input.status||"not_scheduled");if(!inspectionStatuses.includes(status))throw new Error("Invalid inspection status");
 const record=(await db().insert(realEstateInspections).values({id:uid("inspection"),tenantId:scope.tenantId,organizationId:transaction.organizationId,transactionId,inspectorName:String(input.inspectorName||"")||null,inspectorCompany:String(input.inspectorCompany||"")||null,inspectorEmail:String(input.inspectorEmail||"")||null,inspectorPhone:String(input.inspectorPhone||"")||null,scheduledAt:String(input.scheduledAt||"")||null,status,summary:String(input.summary||""),notes:String(input.notes||""),clientVisible:input.clientVisible!==false}).returning())[0];
 await audit(scope,membershipId,transaction.organizationId,transactionId,"inspection",record.id,"inspection_created");
 if(record.scheduledAt){await enqueueCalendarJobs(scope,membershipId,"inspection",record.id);await db().insert(realEstateReminders).values({id:uid("reminder"),tenantId:scope.tenantId,entityType:"inspection",entityId:record.id,title:"Upcoming property inspection",remindAt:new Date(new Date(record.scheduledAt).getTime()-86400000).toISOString(),dedupeKey:`inspection:${record.id}:24h`}).onConflictDoNothing()}
 return record;
}
export async function saveEscrow(scope:DataScope,membershipId:string,transactionId:string,input:Record<string,unknown>){
 const transaction=await findTransaction(scope,transactionId);if(!transaction)throw new Error("Transaction unavailable");const status=String(input.status||"pending");if(!escrowStatuses.includes(status))throw new Error("Invalid escrow status");const amount=input.amountCents==null?null:Number(input.amountCents);if(amount!==null&&(!Number.isSafeInteger(amount)||amount<0))throw new Error("Escrow amount must be non-negative integer cents");
 const record=(await db().insert(realEstateEscrowRecords).values({id:uid("escrow"),tenantId:scope.tenantId,organizationId:transaction.organizationId,transactionId,escrowCompanyName:String(input.escrowCompanyName||"")||null,escrowContactName:String(input.escrowContactName||"")||null,escrowContactEmail:String(input.escrowContactEmail||"")||null,escrowContactPhone:String(input.escrowContactPhone||"")||null,amountCents:amount,dueDate:String(input.dueDate||"")||null,status,referenceNumber:String(input.referenceNumber||"")||null,notes:String(input.notes||""),clientVisible:input.clientVisible!==false}).returning())[0];
 await db().insert(realEstateEscrowEvents).values({id:uid("escrowevt"),tenantId:scope.tenantId,escrowRecordId:record.id,toStatus:status,actorMembershipId:membershipId});
 await audit(scope,membershipId,transaction.organizationId,transactionId,"escrow",record.id,"escrow_created");
 if(record.dueDate){await db().insert(realEstateReminders).values({id:uid("reminder"),tenantId:scope.tenantId,entityType:"escrow",entityId:record.id,title:"Escrow deadline approaching",remindAt:new Date(new Date(record.dueDate).getTime()-86400000).toISOString(),dedupeKey:`escrow:${record.id}:24h`}).onConflictDoNothing();await enqueueJob(scope,transaction.organizationId,membershipId,{jobType:"transaction.milestone.reminder",payload:{milestoneId:record.id},idempotencyKey:`escrow-reminder:${record.id}`,scheduledAt:new Date(new Date(record.dueDate).getTime()-86400000).toISOString()})}
 return record;
}
export async function changeEscrowStatus(scope:DataScope,membershipId:string,id:string,status:string){
 if(!escrowStatuses.includes(status))throw new Error("Invalid escrow status");return db().transaction(async tx=>{const current=(await tx.select().from(realEstateEscrowRecords).where(and(eq(realEstateEscrowRecords.id,id),eq(realEstateEscrowRecords.tenantId,scope.tenantId),isNull(realEstateEscrowRecords.deletedAt))).for("update").limit(1))[0];if(!current||!await findTransaction(scope,current.transactionId))throw new Error("Escrow record unavailable");const record=(await tx.update(realEstateEscrowRecords).set({status,updatedAt:now(),...(status==="deposited"&&{depositDate:now()}),...(status==="verified"&&{verifiedAt:now()}),...(["released","returned","forfeited"].includes(status)&&{releaseDate:now()})}).where(eq(realEstateEscrowRecords.id,id)).returning())[0];await tx.insert(realEstateEscrowEvents).values({id:uid("escrowevt"),tenantId:scope.tenantId,escrowRecordId:id,fromStatus:current.status,toStatus:status,actorMembershipId:membershipId});return record});
}
export async function addParticipant(scope:DataScope,membershipId:string,transactionId:string,input:Record<string,unknown>){const transaction=await findTransaction(scope,transactionId);if(!transaction)throw new Error("Transaction unavailable");const name=String(input.name||"").trim(),role=String(input.role||"other");if(!name)throw new Error("Participant name is required");const record=(await db().insert(realEstateTransactionParticipants).values({id:uid("participant"),tenantId:scope.tenantId,organizationId:transaction.organizationId,transactionId,role,membershipId:String(input.membershipId||"")||null,portalUserId:String(input.portalUserId||"")||null,name,email:String(input.email||"")||null,phone:String(input.phone||"")||null,clientVisible:input.clientVisible===true}).returning())[0];await audit(scope,membershipId,transaction.organizationId,transactionId,"participant",record.id,"transaction_participant_added");return record}
export async function addMilestone(scope:DataScope,membershipId:string,transactionId:string,input:Record<string,unknown>){const transaction=await findTransaction(scope,transactionId);if(!transaction)throw new Error("Transaction unavailable");const title=String(input.title||"").trim();if(!title)throw new Error("Milestone title is required");const record=(await db().insert(realEstateTransactionMilestones).values({id:uid("mile"),tenantId:scope.tenantId,organizationId:transaction.organizationId,transactionId,milestoneType:String(input.milestoneType||"custom"),title,dueAt:String(input.dueAt||"")||null,status:"pending",clientVisible:input.clientVisible!==false,manuallyAdjusted:true}).returning())[0];await audit(scope,membershipId,transaction.organizationId,transactionId,"milestone",record.id,"transaction_milestone_added");if(record.dueAt){await enqueueCalendarJobs(scope,membershipId,"transaction_milestone",record.id);await enqueueJob(scope,transaction.organizationId,membershipId,{jobType:"transaction.milestone.reminder",payload:{milestoneId:record.id},idempotencyKey:`milestone:${record.id}:reminder`,scheduledAt:new Date(new Date(record.dueAt).getTime()-86400000).toISOString()})}return record}
export async function addInspectionItem(scope:DataScope,membershipId:string,inspectionId:string,input:Record<string,unknown>){const inspection=(await db().select().from(realEstateInspections).where(and(eq(realEstateInspections.id,inspectionId),eq(realEstateInspections.tenantId,scope.tenantId),isNull(realEstateInspections.deletedAt))).limit(1))[0];if(!inspection||!await findTransaction(scope,inspection.transactionId))throw new Error("Inspection unavailable");const record=(await db().insert(realEstateInspectionItems).values({id:uid("item"),tenantId:scope.tenantId,inspectionId,title:String(input.title||"").trim(),category:String(input.category||"")||null,severity:String(input.severity||"normal"),description:String(input.description||""),clientVisible:input.clientVisible!==false}).returning())[0];await audit(scope,membershipId,inspection.organizationId,inspection.transactionId,"inspection_item",record.id,"inspection_item_added");return record}
export async function addRepairRequest(scope:DataScope,membershipId:string,inspectionId:string,input:Record<string,unknown>){const inspection=(await db().select().from(realEstateInspections).where(and(eq(realEstateInspections.id,inspectionId),eq(realEstateInspections.tenantId,scope.tenantId),isNull(realEstateInspections.deletedAt))).limit(1))[0];if(!inspection||!await findTransaction(scope,inspection.transactionId))throw new Error("Inspection unavailable");const record=(await db().insert(realEstateRepairRequests).values({id:uid("repair"),tenantId:scope.tenantId,inspectionId,title:String(input.title||"").trim(),description:String(input.description||""),category:String(input.category||"")||null,priority:String(input.priority||"normal"),estimatedCostCents:input.estimatedCostCents==null?null:Number(input.estimatedCostCents),requestedResolution:String(input.requestedResolution||"")||null,status:"requested",assignedTo:String(input.assignedTo||"")||null,dueDate:String(input.dueDate||"")||null,clientVisible:input.clientVisible!==false}).returning())[0];await db().insert(realEstateRepairUpdates).values({id:uid("repairupdate"),tenantId:scope.tenantId,repairRequestId:record.id,actorMembershipId:membershipId,status:"requested",message:"Repair request created"});await audit(scope,membershipId,inspection.organizationId,inspection.transactionId,"repair_request",record.id,"repair_request_created");return record}
