import { and, eq, isNull, or, sql } from "drizzle-orm";
import { realEstateAuditEvents, realEstateCommissionPlans, realEstateTransactionCommissions, realEstateTransactions } from "@/lib/db/schema";
import { db } from "../repositories"; import type { DataScope } from "../access"; import { calculateCommission } from "./commission"; import { findTransaction } from "./repository";
const uid=(kind:string)=>`re_${kind}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,10)}`;
const scoped=(scope:DataScope)=>and(eq(realEstateTransactions.tenantId,scope.tenantId),isNull(realEstateTransactions.deletedAt),["broker_owner","administrator","office_manager"].includes(scope.role)?undefined:or(eq(realEstateTransactions.listingAgentMembershipId,scope.membershipId||"__none__"),eq(realEstateTransactions.buyerAgentMembershipId,scope.membershipId||"__none__"),eq(realEstateTransactions.transactionCoordinatorMembershipId,scope.membershipId||"__none__")));
export async function transactionReport(scope:DataScope){
 const rows=await db().select({status:realEstateTransactions.status,count:sql<number>`count(*)::int`,volumeCents:sql<number>`coalesce(sum(${realEstateTransactions.purchasePriceCents}),0)::bigint`}).from(realEstateTransactions).where(scoped(scope)).groupBy(realEstateTransactions.status);
 const total=rows.reduce((sum,row)=>sum+Number(row.count),0),volume=rows.reduce((sum,row)=>sum+Number(row.volumeCents),0);return{byStatus:rows,total,volumeCents:volume,averagePriceCents:total?Math.round(volume/total):0};
}
export async function saveCommissionEstimate(scope:DataScope,membershipId:string,transactionId:string,input:{name?:string;rateBasisPoints?:number;flatAmountCents?:number;brokerageSplitBasisPoints:number;adjustmentsCents?:number[]}){
 const transaction=await findTransaction(scope,transactionId);if(!transaction)throw new Error("Transaction unavailable");const amount=transaction.purchasePriceCents??transaction.listPriceCents;if(!amount)throw new Error("Transaction amount is required");
 const calculation=calculateCommission({transactionAmountCents:amount,rateBasisPoints:input.rateBasisPoints,flatAmountCents:input.flatAmountCents,brokerageSplitBasisPoints:input.brokerageSplitBasisPoints,adjustmentsCents:input.adjustmentsCents});
 return db().transaction(async tx=>{const plan=(await tx.insert(realEstateCommissionPlans).values({id:uid("commissionplan"),tenantId:scope.tenantId,organizationId:transaction.organizationId,name:input.name||"Transaction estimate",calculationType:input.flatAmountCents==null?"percentage":"flat",rateBasisPoints:input.rateBasisPoints,flatAmountCents:input.flatAmountCents,brokerSplitBasisPoints:input.brokerageSplitBasisPoints,agentSplitBasisPoints:10000-input.brokerageSplitBasisPoints}).returning())[0];const estimate=(await tx.insert(realEstateTransactionCommissions).values({id:uid("commission"),tenantId:scope.tenantId,organizationId:transaction.organizationId,transactionId,membershipId,planId:plan.id,snapshot:{transactionAmountCents:amount,rateBasisPoints:input.rateBasisPoints??0,flatAmountCents:input.flatAmountCents??0,brokerageSplitBasisPoints:input.brokerageSplitBasisPoints,label:"Estimate only"},...calculation}).returning())[0];await tx.insert(realEstateAuditEvents).values({id:uid("audit"),tenantId:scope.tenantId,organizationId:transaction.organizationId,actorType:"membership",actorMembershipId:membershipId,action:"commission_estimate_created",resourceType:"commission",resourceId:estimate.id,transactionId,safeMetadata:{grossCommissionCents:calculation.grossCommissionCents}});return estimate});
}
