"use client";
import { useCallback, useEffect, useState } from "react";
import { storedPin } from "@/components/admin/Dashboard";
import { demoTenant } from "@/lib/real-estate/fixtures";
const headers = () => ({ "Content-Type": "application/json", "x-snaplink-pin": storedPin(), "x-real-estate-tenant": demoTenant.id });
export default function AutomationManager() {
  const [items, setItems] = useState<Record<string, unknown>[]>([]), [name, setName] = useState(""), [trigger, setTrigger] = useState("lead_created");
  const load = useCallback(async () => { const r = await fetch("/api/real-estate/automation", { headers: headers() }), d = await r.json(); if (r.ok) setItems(d.workflows || []); }, []); useEffect(() => { load(); }, [load]);
  async function save(e: React.FormEvent) { e.preventDefault(); await fetch("/api/real-estate/automation", { method: "POST", headers: headers(), body: JSON.stringify({ name, trigger, steps: [{ type: "wait", minutes: 30 }, { type: "send_email" }] }) }); setName(""); load(); }
  return <div className="mx-auto max-w-6xl p-6"><h1 className="font-display text-4xl">Automation</h1><p className="mt-2 text-[#AAA9A2]">Tenant-scoped workflows with pause, retry, cancellation, and durable run history.</p><form onSubmit={save} className="mt-7 grid gap-3 rounded-2xl border border-white/10 bg-[#20231F] p-5 sm:grid-cols-[1fr_260px_auto]"><input required value={name} onChange={e => setName(e.target.value)} placeholder="Workflow name" className="rounded-xl bg-[#181A17] px-4 py-3"/><select value={trigger} onChange={e => setTrigger(e.target.value)} className="rounded-xl bg-[#181A17] px-4">{["lead_created","lead_updated","lead_converted","property_published","showing_scheduled","showing_completed","open_house_registered","open_house_completed","appointment_scheduled","task_due","campaign_published","manual"].map(x => <option key={x}>{x}</option>)}</select><button className="rounded-xl bg-[#B99A5B] px-5 font-semibold text-[#181A17]">Create</button></form><div className="mt-5 space-y-3">{items.map(item => <article key={String(item.id)} className="rounded-2xl border border-white/10 bg-[#20231F] p-5"><div className="flex justify-between"><strong>{String(item.name)}</strong><span className="text-xs uppercase text-[#D1B06A]">{String(item.status)}</span></div><p className="mt-2 text-sm text-[#AAA9A2]">Trigger: {String(item.trigger).replaceAll("_", " ")} · {(item.steps as unknown[]).length} steps</p></article>)}</div></div>;
}
