"use client";
import { useEffect, useMemo, useState } from "react";
import { storedPin } from "@/components/admin/Dashboard";
import { demoTenant } from "@/lib/real-estate/fixtures";
export default function CalendarView() {
  const [events, setEvents] = useState<Record<string, unknown>[]>([]), [view, setView] = useState("month");
  const [reminder, setReminder] = useState({ title: "", remindAt: "", entityType: "leads", entityId: "", channels: ["in_app"] });
  useEffect(() => { fetch("/api/real-estate/calendar/events", { headers: { "x-snaplink-pin": storedPin(), "x-real-estate-tenant": demoTenant.id } }).then(r => r.json()).then(d => setEvents(d.events || [])); }, []);
  const grouped = useMemo(() => Object.entries(Object.groupBy(events, event => new Date(String(event.startsAt)).toLocaleDateString())), [events]);
  async function addReminder(e: React.FormEvent) { e.preventDefault(); await fetch("/api/real-estate/reminders", { method: "POST", headers: { "Content-Type": "application/json", "x-snaplink-pin": storedPin(), "x-real-estate-tenant": demoTenant.id }, body: JSON.stringify({ ...reminder, dedupeKey: `${reminder.entityType}:${reminder.entityId}:${reminder.remindAt}` }) }); window.location.reload(); }
  return <div className="mx-auto max-w-7xl p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-[#B99A5B]">Unified schedule</p><h1 className="mt-2 font-display text-4xl">Calendar</h1></div><div className="flex gap-2">{["month","week","agenda"].map(x => <button key={x} onClick={() => setView(x)} className={`rounded-xl px-4 py-2 text-sm ${view === x ? "bg-[#B99A5B] text-[#181A17]" : "border border-white/10"}`}>{x}</button>)}<a href="/api/real-estate/calendar/feed" className="rounded-xl border border-white/10 px-4 py-2 text-sm">Export ICS</a></div></div><form onSubmit={addReminder} className="mt-6 grid gap-3 rounded-2xl border border-white/10 bg-[#20231F] p-4 sm:grid-cols-2 lg:grid-cols-5"><input required placeholder="Reminder" value={reminder.title} onChange={e => setReminder({ ...reminder, title: e.target.value })} className="rounded-xl bg-[#181A17] px-3 py-2"/><input required type="datetime-local" value={reminder.remindAt} onChange={e => setReminder({ ...reminder, remindAt: e.target.value })} className="rounded-xl bg-[#181A17] px-3 py-2"/><select value={reminder.entityType} onChange={e => setReminder({ ...reminder, entityType: e.target.value })} className="rounded-xl bg-[#181A17] px-3 py-2">{["appointments","tasks","showings","open-houses","campaigns","leads"].map(x => <option key={x}>{x}</option>)}</select><input required placeholder="Related record ID" value={reminder.entityId} onChange={e => setReminder({ ...reminder, entityId: e.target.value })} className="rounded-xl bg-[#181A17] px-3 py-2"/><button className="rounded-xl bg-[#B99A5B] px-4 font-semibold text-[#181A17]">Schedule reminder</button></form><div className={`mt-7 grid gap-4 ${view === "month" ? "md:grid-cols-3 xl:grid-cols-4" : ""}`}>{grouped.map(([date, list]) => <section key={date} className="rounded-2xl border border-white/10 bg-[#20231F] p-4"><h2 className="text-sm font-semibold text-[#D1B06A]">{date}</h2><div className="mt-3 space-y-2">{list?.map(event => <article key={String(event.id)} className="rounded-xl bg-[#181A17] p-3"><p className="text-[10px] uppercase text-[#8F928A]">{String(event.type).replaceAll("_", " ")}</p><p className="mt-1 text-sm">{String(event.title)}</p><p className="mt-1 text-xs text-[#AAA9A2]">{new Date(String(event.startsAt)).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</p></article>)}</div></section>)}</div></div>;
}
