"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { storedPin } from "@/components/admin/Dashboard";
import { demoTenant } from "@/lib/real-estate/fixtures";
const auth = () => ({ "Content-Type": "application/json", "x-snaplink-pin": storedPin(), "x-real-estate-tenant": demoTenant.id });
const input = "rounded-xl border border-white/10 bg-[#181A17] px-4 py-3 text-sm";

export default function CommunicationCenter({ view = "history" }: { view?: "history" | "new" | "templates" }) {
  const [records, setRecords] = useState<Record<string, unknown>[]>([]), [search, setSearch] = useState(""), [status, setStatus] = useState(""), [page, setPage] = useState(1), [total, setTotal] = useState(0);
  const [form, setForm] = useState({ channel: "email", recipient: "", subject: "", body: "", purpose: "transactional", status: "draft", scheduledAt: "", language: "en", templateType: "custom" });
  const load = useCallback(async () => {
    const path = view === "templates" ? "/api/real-estate/communication-templates" : `/api/real-estate/communications?search=${encodeURIComponent(search)}&status=${status}&page=${page}`;
    const r = await fetch(path, { headers: auth() }), d = await r.json(); if (r.ok) { setRecords(d.templates || d.records || []); setTotal(d.total || 0); }
  }, [view, search, status, page]);
  useEffect(() => { load(); }, [load]);
  async function save(e: React.FormEvent) { e.preventDefault(); const endpoint = view === "templates" ? "/api/real-estate/communication-templates" : "/api/real-estate/communications"; const payload = view === "templates" ? { ...form, name: form.subject } : form; const r = await fetch(endpoint, { method: "POST", headers: auth(), body: JSON.stringify(payload) }); if (r.ok) { setForm({ channel: "email", recipient: "", subject: "", body: "", purpose: "transactional", status: "draft", scheduledAt: "", language: "en", templateType: "custom" }); load(); } else alert((await r.json()).error); }
  return <div className="mx-auto max-w-7xl p-4 sm:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.22em] text-[#B99A5B]">Communications</p><h1 className="mt-2 font-display text-4xl">{view === "new" ? "Compose" : view === "templates" ? "Templates" : "Delivery history"}</h1></div><nav className="flex gap-2 text-sm"><Link className="rounded-lg border border-white/10 px-3 py-2" href="/real-estate/communications">Inbox</Link><Link className="rounded-lg border border-white/10 px-3 py-2" href="/real-estate/communications/new">New</Link><Link className="rounded-lg border border-white/10 px-3 py-2" href="/real-estate/communications/templates">Templates</Link><Link className="rounded-lg border border-white/10 px-3 py-2" href="/real-estate/communications/history">History</Link></nav></div>
    {(view === "new" || view === "templates") && <form onSubmit={save} className="mt-7 grid gap-4 rounded-2xl border border-white/10 bg-[#20231F] p-5 sm:grid-cols-2"><select className={input} value={form.channel} onChange={e => setForm({ ...form, channel: e.target.value })}><option value="email">Email</option><option value="sms">SMS</option></select>{view === "new" ? <input className={input} required placeholder="Recipient" value={form.recipient} onChange={e => setForm({ ...form, recipient: e.target.value })}/> : <select className={input} value={form.language} onChange={e => setForm({ ...form, language: e.target.value })}><option value="en">English</option><option value="es">Spanish</option></select>}{view === "templates" && <select className={`${input} sm:col-span-2`} value={form.templateType} onChange={e => setForm({ ...form, templateType: e.target.value })}>{["lead_welcome","buyer_follow_up","seller_follow_up","showing_confirmation","showing_reminder","showing_follow_up","open_house_registration","open_house_reminder","open_house_follow_up","property_inquiry","price_reduction","property_published","campaign","appointment","task_reminder","custom"].map(x => <option key={x}>{x.replaceAll("_", " ")}</option>)}</select>}<input className={`${input} sm:col-span-2`} required placeholder={view === "templates" ? "Template name / subject" : "Subject"} value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })}/><textarea className={`${input} sm:col-span-2`} rows={8} required placeholder="Message. Use {{first_name}}, {{property_title}}, {{agent_name}}…" value={form.body} onChange={e => setForm({ ...form, body: e.target.value })}/>{view === "new" && <><select className={input} value={form.purpose} onChange={e => setForm({ ...form, purpose: e.target.value })}><option value="transactional">Transactional</option><option value="marketing">Marketing</option></select><select className={input} value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option value="draft">Save draft</option><option value="queued">Queue now</option><option value="scheduled">Schedule</option></select></>}<button className="rounded-xl bg-[#B99A5B] px-5 py-3 font-semibold text-[#181A17]">{view === "templates" ? "Save template" : "Save message"}</button></form>}
    {view !== "new" && <><div className="mt-7 grid gap-3 sm:grid-cols-[1fr_220px]"><input className={input} placeholder="Search recipient or content" value={search} onChange={e => setSearch(e.target.value)}/>{view !== "templates" && <select className={input} value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{["draft","scheduled","queued","sent","delivered","failed","cancelled","blocked"].map(x => <option key={x}>{x}</option>)}</select>}</div><div className="mt-4 space-y-3">{records.map(item => <article key={String(item.id)} className="rounded-2xl border border-white/10 bg-[#20231F] p-5"><div className="flex justify-between gap-4"><strong>{String(item.name || item.subject || item.recipient)}</strong><span className="text-xs uppercase text-[#D1B06A]">{String(item.status || item.channel)}</span></div><p className="mt-2 line-clamp-2 text-sm text-[#AAA9A2]">{String(item.body || "")}</p></article>)}</div>{total > 20 && <div className="mt-5 flex gap-2"><button disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</button><button disabled={page * 20 >= total} onClick={() => setPage(p => p + 1)}>Next</button></div>}</>}
  </div>;
}
