"use client";
import { useEffect, useState } from "react";
import { storedPin } from "@/components/admin/Dashboard";
import { demoTenant } from "@/lib/real-estate/fixtures";
const headers = () => ({ "Content-Type": "application/json", "x-snaplink-pin": storedPin(), "x-real-estate-tenant": demoTenant.id });
export default function IntegrationSettings() {
  const [data,setData]=useState<Record<string,unknown>>({}),[recipient,setRecipient]=useState(""),[channel,setChannel]=useState("email");
  useEffect(()=>{fetch("/api/real-estate/integrations/status",{headers:headers()}).then(r=>r.json()).then(setData)},[]);
  const providers=(data.providers||{}) as Record<string,unknown>, jobs=(data.jobs||{}) as Record<string,unknown>, calendars=(data.calendars||[]) as Record<string,unknown>[];
  async function test(){if(!confirm(`Send an explicit ${channel} provider test?`))return;const r=await fetch("/api/real-estate/integrations/test",{method:"POST",headers:headers(),body:JSON.stringify({channel,recipient,confirmed:true})});alert(r.ok?"Test queued":(await r.json()).error)}
  return <div className="mx-auto max-w-6xl p-6"><h1 className="font-display text-4xl">Integration settings</h1><div className="mt-7 grid gap-4 md:grid-cols-3">{["emailProvider","smsProvider","webhookReady","jobsReady","encryptionReady","testMode"].map(k=><article key={k} className="rounded-2xl border border-white/10 bg-[#20231F] p-5"><p className="text-xs uppercase text-[#AAA9A2]">{k.replaceAll(/([A-Z])/g," $1")}</p><p className="mt-2 text-xl text-[#D1B06A]">{String(providers[k]??"unconfigured")}</p></article>)}</div><section className="mt-6 rounded-2xl border border-white/10 bg-[#20231F] p-5"><h2 className="font-display text-2xl">Explicit test send</h2><div className="mt-4 grid gap-3 sm:grid-cols-[160px_1fr_auto]"><select value={channel} onChange={e=>setChannel(e.target.value)} className="rounded-xl bg-[#181A17] px-4"><option>email</option><option>sms</option></select><input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Consented recipient" className="rounded-xl bg-[#181A17] px-4 py-3"/><button onClick={test} className="rounded-xl bg-[#B99A5B] px-5 font-semibold text-[#181A17]">Send test</button></div></section><section className="mt-6 rounded-2xl border border-white/10 bg-[#20231F] p-5"><h2 className="font-display text-2xl">Calendars</h2><div className="mt-4 flex flex-wrap gap-3"><a href="/api/real-estate/calendar/google/connect" className="rounded-xl border border-white/10 px-4 py-3">Connect Google</a><a href="/api/real-estate/calendar/microsoft/connect" className="rounded-xl border border-white/10 px-4 py-3">Connect Microsoft</a><a href="/real-estate/calendar/settings" className="rounded-xl border border-white/10 px-4 py-3">Calendar settings</a></div>{calendars.map(c=><p key={String(c.id)} className="mt-3 text-sm">{String(c.provider)} · {String(c.status)} · Last sync {String(c.lastSyncedAt||"never")}</p>)}</section><a href="/real-estate/settings/jobs" className="mt-6 inline-block text-[#D1B06A]">Inspect jobs ({String(jobs.dead_letter||0)} dead letter)</a></div>;
}
